// Code generated by sqlc. DO NOT EDIT.

package querier

import (
	"database/sql"
)

type Product struct {
	Name      string
	Price     int64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}
