GET http://localhost:8080/greet HTTP/1.1

###

POST http://localhost:8080/uppercase HTTP/1.1

{
    "s": ""
}

###

POST http://localhost:8080/count HTTP/1.1

{
    "s": "test"
}

###

GET http://localhost:8080/greet HTTP/1.1

#
#
### Product Service

POST http://localhost:8080/products HTTP/1.1

{
    "name": "test",
    "price": 15000
}

###

GET http://localhost:8080/products/a HTTP/1.1

#
#
### E-Money Service


POST http://localhost:8080/accounts HTTP/1.1

{}

###

GET http://localhost:8080/accounts/db87651b-84bb-42af-abaf-8f9efda8746e HTTP/1.1

###

GET http://localhost:8080/accounts/9b63c29b-b1ce-4b7b-b6bd-55e9119d37ee HTTP/1.1

###

POST http://localhost:8080/topups HTTP/1.

{
    "account_id": "db87651b-84bb-42af-abaf-8f9efda8746e",
    "amount": 10000
}

###

POST http://localhost:8080/transfers HTTP/1.

{
    "from_account_id": "db87651b-84bb-42af-abaf-8f9efda8746e", 
    "to_account_id": "9b63c29b-b1ce-4b7b-b6bd-55e9119d37ee",
    "amount": 2000
}