GET http://localhost:8080/greet HTTP/1.1

###

POST http://localhost:8080/uppercase HTTP/1.1

{
    "s": ""
}

###

POST http://localhost:8080/count HTTP/1.1

{
    "s": "test"
}

###

GET http://localhost:8080/greet HTTP/1.1

#
#
### Product Service

POST http://localhost:8080/products HTTP/1.1

{
    "name": "test",
    "price": 15000
}

###

GET http://localhost:8080/products/a HTTP/1.1

#
#
### E-Money Service


POST http://localhost:8080/accounts HTTP/1.1

{}

###

GET http://localhost:8080/accounts/bac2191d-e241-47ae-8fa6-2783cdad214a HTTP/1.1

###

GET http://localhost:8080/accounts/ce636cde-57c5-4df7-9b63-30b27b89ce98 HTTP/1.1

###

POST http://localhost:8080/topups HTTP/1.

{
    "account_id": "bac2191d-e241-47ae-8fa6-2783cdad214a",
    "amount": 10000
}

###

POST http://localhost:8080/transfers HTTP/1.

{
    "from_account_id": "bac2191d-e241-47ae-8fa6-2783cdad214a", 
    "to_account_id": "ce636cde-57c5-4df7-9b63-30b27b89ce98",
    "amount": 2000
}