output   = "./database/model"
pkgname  = "model"
wipe     = true

[psql]
dbname = "catalog"
host   = "localhost"
port   = 5432
user   = "postgres"
pass   = "password"
sslmode = "disable"
blacklist = ["schema_migrations"]