// Code generated by sqlc. DO NOT EDIT.

package querier

import (
	"context"
)

type Querier interface {
	FindProduct(ctx context.Context, name string) (Product, error)
	InsertProduct(ctx context.Context, arg InsertProductParams) (Product, error)
}

var _ Querier = (*Queries)(nil)
