output     = "./internal/postgres/models"
wipe       = true

[psql]
dbname = "catalog"
host   = "localhost"
port   = 5432
user   = "postgres"
pass   = "password"
sslmode = "disable"
blacklist = ["goose_db_version"]