// Code generated by SQLBoiler 4.2.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

var TableNames = struct {
	Team       string
	TeamMember string
	User       string
}{
	Team:       "team",
	TeamMember: "team_member",
	User:       "user",
}
